"""Adjusting of UserAchievements

Revision ID: 1b159f7f1354
Revises: 77c46666460f
Create Date: 2024-08-29 12:58:56.348186

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1b159f7f1354'
down_revision: Union[str, None] = '77c46666460f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('achievements_user_id_fkey', 'achievements', type_='foreignkey')
    op.drop_column('achievements', 'user_id')
    op.drop_column('achievements', 'is_locked')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('achievements', sa.Column('is_locked', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('achievements', sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=True))
    op.create_foreign_key('achievements_user_id_fkey', 'achievements', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###
